// Fichier généré automatiquement pour contenir la base de données des clubs féminins
export const ALL_WOMENS_CLUBS = [
  {
    "id": "W_ZA_1",
    "ovr": 78,
    "name": "Mamelodi Sundowns Ladies",
    "origin": "ZA",
    "primary": "#FFFF00",
    "secondary": "#000080",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (ZA)",
    "desc": "Ligue 1 Féminine (ZA)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (ZA)"
  },
  {
    "id": "W_ZA_2",
    "ovr": 76,
    "name": "UWC Ladies",
    "origin": "ZA",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (ZA)",
    "desc": "Ligue 1 Féminine (ZA)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (ZA)"
  },
  {
    "id": "W_ZA_3",
    "ovr": 75,
    "name": "TUT Ladies",
    "origin": "ZA",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (ZA)",
    "desc": "Ligue 1 Féminine (ZA)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (ZA)"
  },
  {
    "id": "W_ZA_4",
    "ovr": 74,
    "name": "JVW FC",
    "origin": "ZA",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ZA)",
    "desc": "Ligue 1 Féminine (ZA)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (ZA)"
  },
  {
    "id": "W_ZA_5",
    "ovr": 72,
    "name": "Richmond United",
    "origin": "ZA",
    "primary": "#800000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ZA)",
    "desc": "Ligue 1 Féminine (ZA)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (ZA)"
  },
  {
    "id": "W_ZA_6",
    "ovr": 71,
    "name": "Royal AM Women",
    "origin": "ZA",
    "primary": "#FFD700",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ZA)",
    "desc": "Ligue 1 Féminine (ZA)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (ZA)"
  },
  {
    "id": "W_DZ_7",
    "ovr": 74,
    "name": "Afak Relizane",
    "origin": "DZ",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DZ)",
    "desc": "Ligue 1 Féminine (DZ)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (DZ)"
  },
  {
    "id": "W_DZ_8",
    "ovr": 73,
    "name": "CF Akbou",
    "origin": "DZ",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DZ)",
    "desc": "Ligue 1 Féminine (DZ)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DZ)"
  },
  {
    "id": "W_DZ_9",
    "ovr": 71,
    "name": "FC Constantine",
    "origin": "DZ",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DZ)",
    "desc": "Ligue 1 Féminine (DZ)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (DZ)"
  },
  {
    "id": "W_DZ_10",
    "ovr": 70,
    "name": "AS Sûreté Nationale",
    "origin": "DZ",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DZ)",
    "desc": "Ligue 1 Féminine (DZ)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DZ)"
  },
  {
    "id": "W_DZ_11",
    "ovr": 68,
    "name": "JF Khroub",
    "origin": "DZ",
    "primary": "#FFFFFF",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DZ)",
    "desc": "Ligue 1 Féminine (DZ)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (DZ)"
  },
  {
    "id": "W_DE_12",
    "ovr": 88,
    "name": "Bayern Munich Women",
    "origin": "DE",
    "primary": "#DC052D",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_13",
    "ovr": 87,
    "name": "VfL Wolfsburg Women",
    "origin": "DE",
    "primary": "#65B32E",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_14",
    "ovr": 83,
    "name": "Eintracht Frankfurt Women",
    "origin": "DE",
    "primary": "#E1000F",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_15",
    "ovr": 80,
    "name": "TSG 1899 Hoffenheim Women",
    "origin": "DE",
    "primary": "#005CA9",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_16",
    "ovr": 78,
    "name": "SGS Essen",
    "origin": "DE",
    "primary": "#6A2A82",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_17",
    "ovr": 77,
    "name": "SC Freiburg Women",
    "origin": "DE",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_18",
    "ovr": 76,
    "name": "Bayer Leverkusen Women",
    "origin": "DE",
    "primary": "#E32221",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_19",
    "ovr": 74,
    "name": "Werder Bremen Women",
    "origin": "DE",
    "primary": "#1D904E",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_20",
    "ovr": 73,
    "name": "RB Leipzig Women",
    "origin": "DE",
    "primary": "#FFFFFF",
    "secondary": "#ED1C24",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_DE_21",
    "ovr": 72,
    "name": "1. FC Köln Women",
    "origin": "DE",
    "primary": "#E1000F",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (DE)",
    "desc": "Ligue 1 Féminine (DE)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (DE)"
  },
  {
    "id": "W_EN_22",
    "ovr": 89,
    "name": "Chelsea FC Women",
    "origin": "EN",
    "primary": "#034694",
    "secondary": "#EE242C",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_23",
    "ovr": 88,
    "name": "Arsenal WFC",
    "origin": "EN",
    "primary": "#EF0107",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_24",
    "ovr": 87,
    "name": "Manchester City WFC",
    "origin": "EN",
    "primary": "#6CABDD",
    "secondary": "#1C2C5B",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_25",
    "ovr": 84,
    "name": "Manchester United WFC",
    "origin": "EN",
    "primary": "#DA291C",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_26",
    "ovr": 80,
    "name": "Aston Villa WFC",
    "origin": "EN",
    "primary": "#670E36",
    "secondary": "#95BFE5",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_27",
    "ovr": 79,
    "name": "Tottenham Hotspur FC Women",
    "origin": "EN",
    "primary": "#132257",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_28",
    "ovr": 77,
    "name": "Everton FC Women",
    "origin": "EN",
    "primary": "#003399",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_29",
    "ovr": 78,
    "name": "Liverpool FC Women",
    "origin": "EN",
    "primary": "#C8102E",
    "secondary": "#F6EB61",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_30",
    "ovr": 76,
    "name": "West Ham United Women",
    "origin": "EN",
    "primary": "#7A263A",
    "secondary": "#1BB1E7",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_EN_31",
    "ovr": 75,
    "name": "Leicester City WFC",
    "origin": "EN",
    "primary": "#003090",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (EN)",
    "desc": "Ligue 1 Féminine (EN)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EN)"
  },
  {
    "id": "W_SA_32",
    "ovr": 75,
    "name": "Al Nassr Women",
    "origin": "SA",
    "primary": "#FFFF00",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SA)",
    "desc": "Ligue 1 Féminine (SA)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (SA)"
  },
  {
    "id": "W_SA_33",
    "ovr": 74,
    "name": "Al Hilal Women",
    "origin": "SA",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SA)",
    "desc": "Ligue 1 Féminine (SA)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (SA)"
  },
  {
    "id": "W_SA_34",
    "ovr": 73,
    "name": "Al Shabab Women",
    "origin": "SA",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SA)",
    "desc": "Ligue 1 Féminine (SA)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SA)"
  },
  {
    "id": "W_SA_35",
    "ovr": 72,
    "name": "Al Ittihad Women",
    "origin": "SA",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SA)",
    "desc": "Ligue 1 Féminine (SA)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SA)"
  },
  {
    "id": "W_SA_36",
    "ovr": 71,
    "name": "Al Ahli Women",
    "origin": "SA",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SA)",
    "desc": "Ligue 1 Féminine (SA)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SA)"
  },
  {
    "id": "W_SA_37",
    "ovr": 69,
    "name": "Eastern Flames FC",
    "origin": "SA",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SA)",
    "desc": "Ligue 1 Féminine (SA)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (SA)"
  },
  {
    "id": "W_AR_38",
    "ovr": 77,
    "name": "Boca Juniors Femenino",
    "origin": "AR",
    "primary": "#000080",
    "secondary": "#FFFF00",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AR)",
    "desc": "Ligue 1 Féminine (AR)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (AR)"
  },
  {
    "id": "W_AR_39",
    "ovr": 76,
    "name": "UAI Urquiza",
    "origin": "AR",
    "primary": "#800000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AR)",
    "desc": "Ligue 1 Féminine (AR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AR)"
  },
  {
    "id": "W_AR_40",
    "ovr": 75,
    "name": "River Plate Femenino",
    "origin": "AR",
    "primary": "#FFFFFF",
    "secondary": "#FF0000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AR)",
    "desc": "Ligue 1 Féminine (AR)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AR)"
  },
  {
    "id": "W_AR_41",
    "ovr": 74,
    "name": "Rosario Central Femenino",
    "origin": "AR",
    "primary": "#0000FF",
    "secondary": "#FFFF00",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AR)",
    "desc": "Ligue 1 Féminine (AR)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (AR)"
  },
  {
    "id": "W_AR_42",
    "ovr": 73,
    "name": "San Lorenzo Femenino",
    "origin": "AR",
    "primary": "#000080",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AR)",
    "desc": "Ligue 1 Féminine (AR)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AR)"
  },
  {
    "id": "W_AR_43",
    "ovr": 72,
    "name": "Racing Club Femenino",
    "origin": "AR",
    "primary": "#87CEEB",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AR)",
    "desc": "Ligue 1 Féminine (AR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (AR)"
  },
  {
    "id": "W_AU_44",
    "ovr": 78,
    "name": "Sydney FC Women",
    "origin": "AU",
    "primary": "#66B2FF",
    "secondary": "#000080",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_45",
    "ovr": 77,
    "name": "Melbourne City FC",
    "origin": "AU",
    "primary": "#6CABDD",
    "secondary": "#1C2C5B",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_46",
    "ovr": 76,
    "name": "Melbourne Victory Women",
    "origin": "AU",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_47",
    "ovr": 74,
    "name": "Brisbane Roar Women",
    "origin": "AU",
    "primary": "#FF8C00",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_48",
    "ovr": 73,
    "name": "Western United",
    "origin": "AU",
    "primary": "#000000",
    "secondary": "#32CD32",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_49",
    "ovr": 72,
    "name": "Perth Glory Women",
    "origin": "AU",
    "primary": "#800080",
    "secondary": "#FFA500",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_50",
    "ovr": 71,
    "name": "Adelaide United",
    "origin": "AU",
    "primary": "#FF0000",
    "secondary": "#FFD700",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_AU_51",
    "ovr": 70,
    "name": "Newcastle Jets",
    "origin": "AU",
    "primary": "#0000FF",
    "secondary": "#FF0000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (AU)",
    "desc": "Ligue 1 Féminine (AU)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AU)"
  },
  {
    "id": "W_BE_52",
    "ovr": 78,
    "name": "RSC Anderlecht Women",
    "origin": "BE",
    "primary": "#4B0082",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (BE)",
    "desc": "Ligue 1 Féminine (BE)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (BE)"
  },
  {
    "id": "W_BE_53",
    "ovr": 77,
    "name": "Standard Liège Women",
    "origin": "BE",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (BE)",
    "desc": "Ligue 1 Féminine (BE)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (BE)"
  },
  {
    "id": "W_BE_54",
    "ovr": 76,
    "name": "OH Leuven Women",
    "origin": "BE",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (BE)",
    "desc": "Ligue 1 Féminine (BE)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (BE)"
  },
  {
    "id": "W_BE_55",
    "ovr": 74,
    "name": "Club YLA",
    "origin": "BE",
    "primary": "#0000FF",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BE)",
    "desc": "Ligue 1 Féminine (BE)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BE)"
  },
  {
    "id": "W_BE_56",
    "ovr": 73,
    "name": "KRC Genk Ladies",
    "origin": "BE",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BE)",
    "desc": "Ligue 1 Féminine (BE)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (BE)"
  },
  {
    "id": "W_BE_57",
    "ovr": 72,
    "name": "KAA Gent Ladies",
    "origin": "BE",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BE)",
    "desc": "Ligue 1 Féminine (BE)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BE)"
  },
  {
    "id": "W_BR_58",
    "ovr": 82,
    "name": "Corinthians Feminino",
    "origin": "BR",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_59",
    "ovr": 80,
    "name": "Palmeiras Feminino",
    "origin": "BR",
    "primary": "#006437",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_60",
    "ovr": 79,
    "name": "Ferroviária",
    "origin": "BR",
    "primary": "#800000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_61",
    "ovr": 78,
    "name": "Santos Feminino",
    "origin": "BR",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_62",
    "ovr": 78,
    "name": "São Paulo Feminino",
    "origin": "BR",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_63",
    "ovr": 77,
    "name": "Internacional Feminino",
    "origin": "BR",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_64",
    "ovr": 76,
    "name": "Flamengo Feminino",
    "origin": "BR",
    "primary": "#C8102E",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_65",
    "ovr": 75,
    "name": "Cruzeiro Feminino",
    "origin": "BR",
    "primary": "#0033A0",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_66",
    "ovr": 74,
    "name": "Grêmio Feminino",
    "origin": "BR",
    "primary": "#00A3E0",
    "secondary": "#000000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_BR_67",
    "ovr": 73,
    "name": "Atlético Mineiro Feminino",
    "origin": "BR",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (BR)",
    "desc": "Ligue 1 Féminine (BR)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (BR)"
  },
  {
    "id": "W_CV_68",
    "ovr": 68,
    "name": "Seven Stars",
    "origin": "CV",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CV)",
    "desc": "Ligue 1 Féminine (CV)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CV)"
  },
  {
    "id": "W_CV_69",
    "ovr": 67,
    "name": "Llana FC",
    "origin": "CV",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CV)",
    "desc": "Ligue 1 Féminine (CV)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CV)"
  },
  {
    "id": "W_CV_70",
    "ovr": 66,
    "name": "CS Mindelense",
    "origin": "CV",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CV)",
    "desc": "Ligue 1 Féminine (CV)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CV)"
  },
  {
    "id": "W_CV_71",
    "ovr": 65,
    "name": "FC Batuque",
    "origin": "CV",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CV)",
    "desc": "Ligue 1 Féminine (CV)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CV)"
  },
  {
    "id": "W_CV_72",
    "ovr": 64,
    "name": "Boavista FC",
    "origin": "CV",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CV)",
    "desc": "Ligue 1 Féminine (CV)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CV)"
  },
  {
    "id": "W_CO_73",
    "ovr": 77,
    "name": "América de Cali Femenino",
    "origin": "CO",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CO)",
    "desc": "Ligue 1 Féminine (CO)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CO)"
  },
  {
    "id": "W_CO_74",
    "ovr": 76,
    "name": "Deportivo Cali Femenino",
    "origin": "CO",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CO)",
    "desc": "Ligue 1 Féminine (CO)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CO)"
  },
  {
    "id": "W_CO_75",
    "ovr": 75,
    "name": "Santa Fe Femenino",
    "origin": "CO",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CO)",
    "desc": "Ligue 1 Féminine (CO)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CO)"
  },
  {
    "id": "W_CO_76",
    "ovr": 74,
    "name": "Atlético Nacional Femenino",
    "origin": "CO",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CO)",
    "desc": "Ligue 1 Féminine (CO)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CO)"
  },
  {
    "id": "W_CO_77",
    "ovr": 73,
    "name": "Millonarios Femenino",
    "origin": "CO",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CO)",
    "desc": "Ligue 1 Féminine (CO)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CO)"
  },
  {
    "id": "W_CO_78",
    "ovr": 72,
    "name": "Independiente Medellín",
    "origin": "CO",
    "primary": "#FF0000",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CO)",
    "desc": "Ligue 1 Féminine (CO)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CO)"
  },
  {
    "id": "W_KR_79",
    "ovr": 78,
    "name": "Incheon Hyundai Steel",
    "origin": "KR",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (KR)",
    "desc": "Ligue 1 Féminine (KR)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (KR)"
  },
  {
    "id": "W_KR_80",
    "ovr": 77,
    "name": "Hwacheon KSPO",
    "origin": "KR",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (KR)",
    "desc": "Ligue 1 Féminine (KR)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (KR)"
  },
  {
    "id": "W_KR_81",
    "ovr": 76,
    "name": "Suwon FC Women",
    "origin": "KR",
    "primary": "#000080",
    "secondary": "#FF0000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (KR)",
    "desc": "Ligue 1 Féminine (KR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (KR)"
  },
  {
    "id": "W_KR_82",
    "ovr": 75,
    "name": "Gyeongju KHNP",
    "origin": "KR",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (KR)",
    "desc": "Ligue 1 Féminine (KR)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (KR)"
  },
  {
    "id": "W_KR_83",
    "ovr": 74,
    "name": "Seoul WFC",
    "origin": "KR",
    "primary": "#000000",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (KR)",
    "desc": "Ligue 1 Féminine (KR)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (KR)"
  },
  {
    "id": "W_KR_84",
    "ovr": 72,
    "name": "Sejong Sportstoto",
    "origin": "KR",
    "primary": "#0000FF",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (KR)",
    "desc": "Ligue 1 Féminine (KR)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (KR)"
  },
  {
    "id": "W_CI_85",
    "ovr": 73,
    "name": "Juventus de Yopougon",
    "origin": "CI",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CI)",
    "desc": "Ligue 1 Féminine (CI)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CI)"
  },
  {
    "id": "W_CI_86",
    "ovr": 72,
    "name": "Inter d'Abidjan",
    "origin": "CI",
    "primary": "#0000FF",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CI)",
    "desc": "Ligue 1 Féminine (CI)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CI)"
  },
  {
    "id": "W_CI_87",
    "ovr": 71,
    "name": "Africa Sports",
    "origin": "CI",
    "primary": "#008000",
    "secondary": "#FF0000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CI)",
    "desc": "Ligue 1 Féminine (CI)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CI)"
  },
  {
    "id": "W_CI_88",
    "ovr": 70,
    "name": "ASEC Mimosas",
    "origin": "CI",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CI)",
    "desc": "Ligue 1 Féminine (CI)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CI)"
  },
  {
    "id": "W_CI_89",
    "ovr": 69,
    "name": "Stella Club",
    "origin": "CI",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CI)",
    "desc": "Ligue 1 Féminine (CI)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CI)"
  },
  {
    "id": "W_HR_90",
    "ovr": 74,
    "name": "ŽNK Osijek",
    "origin": "HR",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (HR)",
    "desc": "Ligue 1 Féminine (HR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (HR)"
  },
  {
    "id": "W_HR_91",
    "ovr": 73,
    "name": "ŽNK Split",
    "origin": "HR",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (HR)",
    "desc": "Ligue 1 Féminine (HR)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (HR)"
  },
  {
    "id": "W_HR_92",
    "ovr": 72,
    "name": "ŽNK Dinamo Zagreb",
    "origin": "HR",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (HR)",
    "desc": "Ligue 1 Féminine (HR)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (HR)"
  },
  {
    "id": "W_HR_93",
    "ovr": 71,
    "name": "ŽNK Hajduk Split",
    "origin": "HR",
    "primary": "#FFFFFF",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (HR)",
    "desc": "Ligue 1 Féminine (HR)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (HR)"
  },
  {
    "id": "W_HR_94",
    "ovr": 69,
    "name": "ŽNK Agram",
    "origin": "HR",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (HR)",
    "desc": "Ligue 1 Féminine (HR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (HR)"
  },
  {
    "id": "W_DK_95",
    "ovr": 78,
    "name": "HB Køge",
    "origin": "DK",
    "primary": "#000000",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DK)",
    "desc": "Ligue 1 Féminine (DK)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DK)"
  },
  {
    "id": "W_DK_96",
    "ovr": 77,
    "name": "Fortuna Hjørring",
    "origin": "DK",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DK)",
    "desc": "Ligue 1 Féminine (DK)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DK)"
  },
  {
    "id": "W_DK_97",
    "ovr": 76,
    "name": "Brøndby IF",
    "origin": "DK",
    "primary": "#FFFF00",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (DK)",
    "desc": "Ligue 1 Féminine (DK)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (DK)"
  },
  {
    "id": "W_DK_98",
    "ovr": 75,
    "name": "FC Nordsjælland",
    "origin": "DK",
    "primary": "#FF0000",
    "secondary": "#FFFF00",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DK)",
    "desc": "Ligue 1 Féminine (DK)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DK)"
  },
  {
    "id": "W_DK_99",
    "ovr": 73,
    "name": "KoldingQ",
    "origin": "DK",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DK)",
    "desc": "Ligue 1 Féminine (DK)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DK)"
  },
  {
    "id": "W_DK_100",
    "ovr": 71,
    "name": "AGF Kvindefodbold",
    "origin": "DK",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (DK)",
    "desc": "Ligue 1 Féminine (DK)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (DK)"
  },
  {
    "id": "W_SCO_101",
    "ovr": 78,
    "name": "Rangers WFC",
    "origin": "SCO",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SCO)",
    "desc": "Ligue 1 Féminine (SCO)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (SCO)"
  },
  {
    "id": "W_SCO_102",
    "ovr": 77,
    "name": "Celtic FC Women",
    "origin": "SCO",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SCO)",
    "desc": "Ligue 1 Féminine (SCO)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (SCO)"
  },
  {
    "id": "W_SCO_103",
    "ovr": 76,
    "name": "Glasgow City FC",
    "origin": "SCO",
    "primary": "#FFA500",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SCO)",
    "desc": "Ligue 1 Féminine (SCO)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SCO)"
  },
  {
    "id": "W_SCO_104",
    "ovr": 74,
    "name": "Heart of Midlothian WFC",
    "origin": "SCO",
    "primary": "#800000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SCO)",
    "desc": "Ligue 1 Féminine (SCO)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (SCO)"
  },
  {
    "id": "W_SCO_105",
    "ovr": 73,
    "name": "Hibernian Women",
    "origin": "SCO",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SCO)",
    "desc": "Ligue 1 Féminine (SCO)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SCO)"
  },
  {
    "id": "W_SCO_106",
    "ovr": 71,
    "name": "Partick Thistle WFC",
    "origin": "SCO",
    "primary": "#FFD700",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SCO)",
    "desc": "Ligue 1 Féminine (SCO)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SCO)"
  },
  {
    "id": "W_EG_107",
    "ovr": 74,
    "name": "Wadi Degla",
    "origin": "EG",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EG)",
    "desc": "Ligue 1 Féminine (EG)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (EG)"
  },
  {
    "id": "W_EG_108",
    "ovr": 73,
    "name": "Tutankhamun FC",
    "origin": "EG",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EG)",
    "desc": "Ligue 1 Féminine (EG)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EG)"
  },
  {
    "id": "W_EG_109",
    "ovr": 72,
    "name": "Al Ahly Women",
    "origin": "EG",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EG)",
    "desc": "Ligue 1 Féminine (EG)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (EG)"
  },
  {
    "id": "W_EG_110",
    "ovr": 71,
    "name": "Zamalek Women",
    "origin": "EG",
    "primary": "#FFFFFF",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EG)",
    "desc": "Ligue 1 Féminine (EG)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EG)"
  },
  {
    "id": "W_EG_111",
    "ovr": 70,
    "name": "Pyramids FC Women",
    "origin": "EG",
    "primary": "#000080",
    "secondary": "#87CEEB",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EG)",
    "desc": "Ligue 1 Féminine (EG)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (EG)"
  },
  {
    "id": "W_AE_112",
    "ovr": 70,
    "name": "Abu Dhabi Country Club",
    "origin": "AE",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AE)",
    "desc": "Ligue 1 Féminine (AE)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AE)"
  },
  {
    "id": "W_AE_113",
    "ovr": 69,
    "name": "Al Ain Women",
    "origin": "AE",
    "primary": "#800080",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AE)",
    "desc": "Ligue 1 Féminine (AE)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (AE)"
  },
  {
    "id": "W_AE_114",
    "ovr": 68,
    "name": "Dubai WFC",
    "origin": "AE",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (AE)",
    "desc": "Ligue 1 Féminine (AE)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (AE)"
  },
  {
    "id": "W_AE_115",
    "ovr": 67,
    "name": "Sharjah Women",
    "origin": "AE",
    "primary": "#FFFFFF",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (AE)",
    "desc": "Ligue 1 Féminine (AE)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (AE)"
  },
  {
    "id": "W_EC_116",
    "ovr": 75,
    "name": "Dragonas IDV",
    "origin": "EC",
    "primary": "#000000",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EC)",
    "desc": "Ligue 1 Féminine (EC)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (EC)"
  },
  {
    "id": "W_EC_117",
    "ovr": 74,
    "name": "Barcelona SC Femenino",
    "origin": "EC",
    "primary": "#FFFF00",
    "secondary": "#FF0000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EC)",
    "desc": "Ligue 1 Féminine (EC)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EC)"
  },
  {
    "id": "W_EC_118",
    "ovr": 73,
    "name": "Club Ñañas",
    "origin": "EC",
    "primary": "#FFC0CB",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (EC)",
    "desc": "Ligue 1 Féminine (EC)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EC)"
  },
  {
    "id": "W_EC_119",
    "ovr": 72,
    "name": "LDU Quito Femenino",
    "origin": "EC",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EC)",
    "desc": "Ligue 1 Féminine (EC)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EC)"
  },
  {
    "id": "W_EC_120",
    "ovr": 70,
    "name": "Deportivo Cuenca",
    "origin": "EC",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (EC)",
    "desc": "Ligue 1 Féminine (EC)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (EC)"
  },
  {
    "id": "W_ES_121",
    "ovr": 92,
    "name": "FC Barcelona Femení",
    "origin": "ES",
    "primary": "#004D98",
    "secondary": "#DB0030",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_122",
    "ovr": 86,
    "name": "Real Madrid Femenino",
    "origin": "ES",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_123",
    "ovr": 82,
    "name": "Levante UD Femenino",
    "origin": "ES",
    "primary": "#0000FF",
    "secondary": "#FF0000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_124",
    "ovr": 81,
    "name": "Atlético de Madrid Femenino",
    "origin": "ES",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_125",
    "ovr": 80,
    "name": "Real Sociedad Femenino",
    "origin": "ES",
    "primary": "#0033A0",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_126",
    "ovr": 78,
    "name": "Athletic Club Femenino",
    "origin": "ES",
    "primary": "#EE2523",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_127",
    "ovr": 77,
    "name": "Madrid CFF",
    "origin": "ES",
    "primary": "#FFFFFF",
    "secondary": "#FFC0CB",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_128",
    "ovr": 76,
    "name": "Sevilla FC Femenino",
    "origin": "ES",
    "primary": "#FFFFFF",
    "secondary": "#FF0000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_129",
    "ovr": 75,
    "name": "UDG Tenerife",
    "origin": "ES",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_ES_130",
    "ovr": 74,
    "name": "Valencia CF Femenino",
    "origin": "ES",
    "primary": "#FFFFFF",
    "secondary": "#000000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (ES)",
    "desc": "Ligue 1 Féminine (ES)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (ES)"
  },
  {
    "id": "W_US_131",
    "ovr": 86,
    "name": "NJ/NY Gotham FC",
    "origin": "US",
    "primary": "#000000",
    "secondary": "#00FFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_132",
    "ovr": 85,
    "name": "Portland Thorns FC",
    "origin": "US",
    "primary": "#C02032",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_133",
    "ovr": 85,
    "name": "San Diego Wave FC",
    "origin": "US",
    "primary": "#000000",
    "secondary": "#FF1493",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_134",
    "ovr": 83,
    "name": "Washington Spirit",
    "origin": "US",
    "primary": "#000000",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_135",
    "ovr": 82,
    "name": "Seattle Reign FC",
    "origin": "US",
    "primary": "#0033A0",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_136",
    "ovr": 81,
    "name": "North Carolina Courage",
    "origin": "US",
    "primary": "#002D72",
    "secondary": "#E31837",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_137",
    "ovr": 80,
    "name": "Angel City FC",
    "origin": "US",
    "primary": "#000000",
    "secondary": "#FFC0CB",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_138",
    "ovr": 79,
    "name": "Orlando Pride",
    "origin": "US",
    "primary": "#5E2750",
    "secondary": "#0077C8",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_139",
    "ovr": 77,
    "name": "Racing Louisville FC",
    "origin": "US",
    "primary": "#3B0083",
    "secondary": "#A06DB3",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_US_140",
    "ovr": 76,
    "name": "Chicago Red Stars",
    "origin": "US",
    "primary": "#41B6E6",
    "secondary": "#E4002B",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (US)",
    "desc": "Ligue 1 Féminine (US)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (US)"
  },
  {
    "id": "W_FR_141",
    "ovr": 88,
    "name": "Olympique Lyonnais Féminin",
    "origin": "FR",
    "primary": "#FFFFFF",
    "secondary": "#DA291C",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_142",
    "ovr": 85,
    "name": "Paris Saint-Germain",
    "origin": "FR",
    "primary": "#004170",
    "secondary": "#DA291C",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_143",
    "ovr": 81,
    "name": "Paris FC",
    "origin": "FR",
    "primary": "#003366",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_144",
    "ovr": 78,
    "name": "FC Fleury 91",
    "origin": "FR",
    "primary": "#E30613",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_145",
    "ovr": 77,
    "name": "Montpellier HSC",
    "origin": "FR",
    "primary": "#F36C21",
    "secondary": "#002C5B",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_146",
    "ovr": 76,
    "name": "Stade de Reims",
    "origin": "FR",
    "primary": "#E30613",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_147",
    "ovr": 74,
    "name": "Girondins de Bordeaux",
    "origin": "FR",
    "primary": "#001b50",
    "secondary": "#ffffff",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_148",
    "ovr": 73,
    "name": "EA Guingamp",
    "origin": "FR",
    "primary": "#E30613",
    "secondary": "#000000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_149",
    "ovr": 72,
    "name": "Dijon FCO",
    "origin": "FR",
    "primary": "#ED1C24",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_FR_150",
    "ovr": 71,
    "name": "Le Havre AC",
    "origin": "FR",
    "primary": "#87CEEB",
    "secondary": "#000080",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (FR)",
    "desc": "Ligue 1 Féminine (FR)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (FR)"
  },
  {
    "id": "W_GH_151",
    "ovr": 75,
    "name": "Ampem Darkoa Ladies",
    "origin": "GH",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (GH)",
    "desc": "Ligue 1 Féminine (GH)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (GH)"
  },
  {
    "id": "W_GH_152",
    "ovr": 74,
    "name": "Hasaacas Ladies",
    "origin": "GH",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (GH)",
    "desc": "Ligue 1 Féminine (GH)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (GH)"
  },
  {
    "id": "W_GH_153",
    "ovr": 73,
    "name": "Police Ladies",
    "origin": "GH",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (GH)",
    "desc": "Ligue 1 Féminine (GH)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (GH)"
  },
  {
    "id": "W_GH_154",
    "ovr": 72,
    "name": "Prisons Ladies",
    "origin": "GH",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (GH)",
    "desc": "Ligue 1 Féminine (GH)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (GH)"
  },
  {
    "id": "W_GH_155",
    "ovr": 71,
    "name": "LadyStrikers",
    "origin": "GH",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (GH)",
    "desc": "Ligue 1 Féminine (GH)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (GH)"
  },
  {
    "id": "W_GR_156",
    "ovr": 76,
    "name": "PAOK",
    "origin": "GR",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (GR)",
    "desc": "Ligue 1 Féminine (GR)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (GR)"
  },
  {
    "id": "W_GR_157",
    "ovr": 74,
    "name": "AEK Athens Women",
    "origin": "GR",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (GR)",
    "desc": "Ligue 1 Féminine (GR)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (GR)"
  },
  {
    "id": "W_GR_158",
    "ovr": 73,
    "name": "Panathinaikos Women",
    "origin": "GR",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (GR)",
    "desc": "Ligue 1 Féminine (GR)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (GR)"
  },
  {
    "id": "W_GR_159",
    "ovr": 72,
    "name": "OFI Crete Women",
    "origin": "GR",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (GR)",
    "desc": "Ligue 1 Féminine (GR)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (GR)"
  },
  {
    "id": "W_GR_160",
    "ovr": 71,
    "name": "Asteras Tripolis",
    "origin": "GR",
    "primary": "#FFFF00",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (GR)",
    "desc": "Ligue 1 Féminine (GR)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (GR)"
  },
  {
    "id": "W_IQ_161",
    "ovr": 71,
    "name": "Naft Al-Shamal",
    "origin": "IQ",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IQ)",
    "desc": "Ligue 1 Féminine (IQ)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IQ)"
  },
  {
    "id": "W_IQ_162",
    "ovr": 70,
    "name": "Al-Quwa Al-Jawiya",
    "origin": "IQ",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IQ)",
    "desc": "Ligue 1 Féminine (IQ)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IQ)"
  },
  {
    "id": "W_IQ_163",
    "ovr": 69,
    "name": "Ghaz Al-Shamal",
    "origin": "IQ",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IQ)",
    "desc": "Ligue 1 Féminine (IQ)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IQ)"
  },
  {
    "id": "W_IQ_164",
    "ovr": 68,
    "name": "Al-Shorta Women",
    "origin": "IQ",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IQ)",
    "desc": "Ligue 1 Féminine (IQ)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IQ)"
  },
  {
    "id": "W_IR_165",
    "ovr": 75,
    "name": "Khatoon Bam",
    "origin": "IR",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IR)",
    "desc": "Ligue 1 Féminine (IR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IR)"
  },
  {
    "id": "W_IR_166",
    "ovr": 74,
    "name": "Sepahan Women",
    "origin": "IR",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IR)",
    "desc": "Ligue 1 Féminine (IR)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IR)"
  },
  {
    "id": "W_IR_167",
    "ovr": 73,
    "name": "Shahrdari Sirjan",
    "origin": "IR",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IR)",
    "desc": "Ligue 1 Féminine (IR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IR)"
  },
  {
    "id": "W_IR_168",
    "ovr": 72,
    "name": "Malavan Women",
    "origin": "IR",
    "primary": "#FFFFFF",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IR)",
    "desc": "Ligue 1 Féminine (IR)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IR)"
  },
  {
    "id": "W_IR_169",
    "ovr": 71,
    "name": "Zob Ahan Women",
    "origin": "IR",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IR)",
    "desc": "Ligue 1 Féminine (IR)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IR)"
  },
  {
    "id": "W_IT_170",
    "ovr": 84,
    "name": "AS Roma Women",
    "origin": "IT",
    "primary": "#8E1F2F",
    "secondary": "#F0BC42",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_171",
    "ovr": 83,
    "name": "Juventus Women",
    "origin": "IT",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_172",
    "ovr": 81,
    "name": "AC Milan Women",
    "origin": "IT",
    "primary": "#FB090B",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_173",
    "ovr": 80,
    "name": "Inter Milan Women",
    "origin": "IT",
    "primary": "#0058A8",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_174",
    "ovr": 78,
    "name": "Fiorentina Women",
    "origin": "IT",
    "primary": "#482E92",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_175",
    "ovr": 76,
    "name": "Sassuolo Women",
    "origin": "IT",
    "primary": "#00523C",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_176",
    "ovr": 74,
    "name": "Como Women",
    "origin": "IT",
    "primary": "#0033A0",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "pace",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_177",
    "ovr": 73,
    "name": "Sampdoria Women",
    "origin": "IT",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_178",
    "ovr": 71,
    "name": "Pomigliano Women",
    "origin": "IT",
    "primary": "#8B0000",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_IT_179",
    "ovr": 70,
    "name": "Napoli Femminile",
    "origin": "IT",
    "primary": "#00BFFF",
    "secondary": "#FFFFFF",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (IT)",
    "desc": "Ligue 1 Féminine (IT)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (IT)"
  },
  {
    "id": "W_JP_180",
    "ovr": 81,
    "name": "Urawa Reds Ladies",
    "origin": "JP",
    "primary": "#E30613",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_181",
    "ovr": 80,
    "name": "INAC Kobe Leonessa",
    "origin": "JP",
    "primary": "#800000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_182",
    "ovr": 79,
    "name": "Tokyo Verdy Beleza",
    "origin": "JP",
    "primary": "#006400",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_183",
    "ovr": 76,
    "name": "Mynavi Sendai Ladies",
    "origin": "JP",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_184",
    "ovr": 75,
    "name": "JEF United Chiba",
    "origin": "JP",
    "primary": "#FFFF00",
    "secondary": "#008000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_185",
    "ovr": 74,
    "name": "Omiya Ardija Ventus",
    "origin": "JP",
    "primary": "#FFA500",
    "secondary": "#000080",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_186",
    "ovr": 73,
    "name": "Sanfrecce Hiroshima",
    "origin": "JP",
    "primary": "#4B0082",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JP_187",
    "ovr": 72,
    "name": "AC Nagano Parceiro",
    "origin": "JP",
    "primary": "#FFA500",
    "secondary": "#000000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (JP)",
    "desc": "Ligue 1 Féminine (JP)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (JP)"
  },
  {
    "id": "W_JO_188",
    "ovr": 73,
    "name": "Amman Club",
    "origin": "JO",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (JO)",
    "desc": "Ligue 1 Féminine (JO)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (JO)"
  },
  {
    "id": "W_JO_189",
    "ovr": 72,
    "name": "Orthodox Club",
    "origin": "JO",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (JO)",
    "desc": "Ligue 1 Féminine (JO)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (JO)"
  },
  {
    "id": "W_JO_190",
    "ovr": 71,
    "name": "Etihad Club",
    "origin": "JO",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (JO)",
    "desc": "Ligue 1 Féminine (JO)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (JO)"
  },
  {
    "id": "W_JO_191",
    "ovr": 69,
    "name": "Al-Nassr",
    "origin": "JO",
    "primary": "#000080",
    "secondary": "#FFFF00",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (JO)",
    "desc": "Ligue 1 Féminine (JO)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (JO)"
  },
  {
    "id": "W_MA_192",
    "ovr": 77,
    "name": "ASFAR Women",
    "origin": "MA",
    "primary": "#000000",
    "secondary": "#FF0000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (MA)",
    "desc": "Ligue 1 Féminine (MA)",
    "preferredStat": "pace",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (MA)"
  },
  {
    "id": "W_MA_193",
    "ovr": 75,
    "name": "Sporting Casablanca",
    "origin": "MA",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (MA)",
    "desc": "Ligue 1 Féminine (MA)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (MA)"
  },
  {
    "id": "W_MA_194",
    "ovr": 74,
    "name": "Wydad AC Women",
    "origin": "MA",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (MA)",
    "desc": "Ligue 1 Féminine (MA)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (MA)"
  },
  {
    "id": "W_MA_195",
    "ovr": 73,
    "name": "Raja CA Women",
    "origin": "MA",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (MA)",
    "desc": "Ligue 1 Féminine (MA)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (MA)"
  },
  {
    "id": "W_MA_196",
    "ovr": 71,
    "name": "SC Chabab Mohammédia",
    "origin": "MA",
    "primary": "#000000",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (MA)",
    "desc": "Ligue 1 Féminine (MA)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (MA)"
  },
  {
    "id": "W_MX_197",
    "ovr": 81,
    "name": "Tigres UANL Femenil",
    "origin": "MX",
    "primary": "#FFD700",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_198",
    "ovr": 80,
    "name": "Monterrey Femenil",
    "origin": "MX",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_199",
    "ovr": 79,
    "name": "Club América Femenil",
    "origin": "MX",
    "primary": "#FFFF00",
    "secondary": "#000080",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_200",
    "ovr": 78,
    "name": "Chivas Femenil",
    "origin": "MX",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_201",
    "ovr": 77,
    "name": "Pachuca Femenil",
    "origin": "MX",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_202",
    "ovr": 75,
    "name": "Toluca Femenil",
    "origin": "MX",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_203",
    "ovr": 74,
    "name": "Juárez Femenil",
    "origin": "MX",
    "primary": "#008000",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_MX_204",
    "ovr": 73,
    "name": "Tijuana Femenil",
    "origin": "MX",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (MX)",
    "desc": "Ligue 1 Féminine (MX)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (MX)"
  },
  {
    "id": "W_NG_205",
    "ovr": 76,
    "name": "Rivers Angels",
    "origin": "NG",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NG)",
    "desc": "Ligue 1 Féminine (NG)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NG)"
  },
  {
    "id": "W_NG_206",
    "ovr": 75,
    "name": "Delta Queens",
    "origin": "NG",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NG)",
    "desc": "Ligue 1 Féminine (NG)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NG)"
  },
  {
    "id": "W_NG_207",
    "ovr": 74,
    "name": "Bayelsa Queens",
    "origin": "NG",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NG)",
    "desc": "Ligue 1 Féminine (NG)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (NG)"
  },
  {
    "id": "W_NG_208",
    "ovr": 73,
    "name": "Nasarawa Amazons",
    "origin": "NG",
    "primary": "#FFFF00",
    "secondary": "#008000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NG)",
    "desc": "Ligue 1 Féminine (NG)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NG)"
  },
  {
    "id": "W_NG_209",
    "ovr": 72,
    "name": "Edo Queens",
    "origin": "NG",
    "primary": "#FF0000",
    "secondary": "#FFFF00",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NG)",
    "desc": "Ligue 1 Féminine (NG)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (NG)"
  },
  {
    "id": "W_NG_210",
    "ovr": 70,
    "name": "FC Robo",
    "origin": "NG",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NG)",
    "desc": "Ligue 1 Féminine (NG)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NG)"
  },
  {
    "id": "W_NO_211",
    "ovr": 79,
    "name": "SK Brann Kvinner",
    "origin": "NO",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NO)",
    "desc": "Ligue 1 Féminine (NO)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NO)"
  },
  {
    "id": "W_NO_212",
    "ovr": 78,
    "name": "Vålerenga",
    "origin": "NO",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NO)",
    "desc": "Ligue 1 Féminine (NO)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (NO)"
  },
  {
    "id": "W_NO_213",
    "ovr": 77,
    "name": "Rosenborg Kvinner",
    "origin": "NO",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NO)",
    "desc": "Ligue 1 Féminine (NO)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NO)"
  },
  {
    "id": "W_NO_214",
    "ovr": 75,
    "name": "LSK Kvinner",
    "origin": "NO",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NO)",
    "desc": "Ligue 1 Féminine (NO)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (NO)"
  },
  {
    "id": "W_NO_215",
    "ovr": 73,
    "name": "Stabæk",
    "origin": "NO",
    "primary": "#000080",
    "secondary": "#87CEEB",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NO)",
    "desc": "Ligue 1 Féminine (NO)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (NO)"
  },
  {
    "id": "W_NO_216",
    "ovr": 71,
    "name": "Kolbotn",
    "origin": "NO",
    "primary": "#FFFFFF",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NO)",
    "desc": "Ligue 1 Féminine (NO)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NO)"
  },
  {
    "id": "W_UZ_217",
    "ovr": 73,
    "name": "Sevinch",
    "origin": "UZ",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (UZ)",
    "desc": "Ligue 1 Féminine (UZ)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (UZ)"
  },
  {
    "id": "W_UZ_218",
    "ovr": 72,
    "name": "Bunyodkor Women",
    "origin": "UZ",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (UZ)",
    "desc": "Ligue 1 Féminine (UZ)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (UZ)"
  },
  {
    "id": "W_UZ_219",
    "ovr": 71,
    "name": "Sogdiana Women",
    "origin": "UZ",
    "primary": "#FFFF00",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (UZ)",
    "desc": "Ligue 1 Féminine (UZ)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (UZ)"
  },
  {
    "id": "W_UZ_220",
    "ovr": 70,
    "name": "Metallurg Women",
    "origin": "UZ",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (UZ)",
    "desc": "Ligue 1 Féminine (UZ)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (UZ)"
  },
  {
    "id": "W_UZ_221",
    "ovr": 69,
    "name": "Pakhtakor Women",
    "origin": "UZ",
    "primary": "#FFFF00",
    "secondary": "#000080",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (UZ)",
    "desc": "Ligue 1 Féminine (UZ)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (UZ)"
  },
  {
    "id": "W_PS_222",
    "ovr": 68,
    "name": "Shabab Al-Amari",
    "origin": "PS",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PS)",
    "desc": "Ligue 1 Féminine (PS)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PS)"
  },
  {
    "id": "W_PS_223",
    "ovr": 67,
    "name": "Orthodox Beit Sahour",
    "origin": "PS",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PS)",
    "desc": "Ligue 1 Féminine (PS)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (PS)"
  },
  {
    "id": "W_PS_224",
    "ovr": 66,
    "name": "Diyar Bethlehem",
    "origin": "PS",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PS)",
    "desc": "Ligue 1 Féminine (PS)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (PS)"
  },
  {
    "id": "W_PS_225",
    "ovr": 65,
    "name": "Sareyyet Ramallah",
    "origin": "PS",
    "primary": "#FFFFFF",
    "secondary": "#FF0000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PS)",
    "desc": "Ligue 1 Féminine (PS)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PS)"
  },
  {
    "id": "W_NL_226",
    "ovr": 81,
    "name": "Ajax Vrouwen",
    "origin": "NL",
    "primary": "#D2122E",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_227",
    "ovr": 80,
    "name": "FC Twente Vrouwen",
    "origin": "NL",
    "primary": "#D2122E",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_228",
    "ovr": 78,
    "name": "PSV Vrouwen",
    "origin": "NL",
    "primary": "#D2122E",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_229",
    "ovr": 75,
    "name": "Fortuna Sittard",
    "origin": "NL",
    "primary": "#FFD700",
    "secondary": "#008000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_230",
    "ovr": 74,
    "name": "ADO Den Haag",
    "origin": "NL",
    "primary": "#006400",
    "secondary": "#FFFF00",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_231",
    "ovr": 72,
    "name": "PEC Zwolle",
    "origin": "NL",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_232",
    "ovr": 71,
    "name": "Feyenoord Vrouwen",
    "origin": "NL",
    "primary": "#D2122E",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_NL_233",
    "ovr": 68,
    "name": "Excelsior",
    "origin": "NL",
    "primary": "#000000",
    "secondary": "#D2122E",
    "tier": 3,
    "leagueName": "Ligue 1 Féminine (NL)",
    "desc": "Ligue 1 Féminine (NL)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (NL)"
  },
  {
    "id": "W_PL_234",
    "ovr": 75,
    "name": "Górnik Łęczna",
    "origin": "PL",
    "primary": "#008000",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PL)",
    "desc": "Ligue 1 Féminine (PL)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (PL)"
  },
  {
    "id": "W_PL_235",
    "ovr": 74,
    "name": "UKS SMS Łódź",
    "origin": "PL",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PL)",
    "desc": "Ligue 1 Féminine (PL)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (PL)"
  },
  {
    "id": "W_PL_236",
    "ovr": 73,
    "name": "Czarni Sosnowiec",
    "origin": "PL",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PL)",
    "desc": "Ligue 1 Féminine (PL)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PL)"
  },
  {
    "id": "W_PL_237",
    "ovr": 72,
    "name": "Śląsk Wrocław",
    "origin": "PL",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PL)",
    "desc": "Ligue 1 Féminine (PL)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PL)"
  },
  {
    "id": "W_PL_238",
    "ovr": 71,
    "name": "Pogoń Szczecin",
    "origin": "PL",
    "primary": "#000080",
    "secondary": "#800000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PL)",
    "desc": "Ligue 1 Féminine (PL)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PL)"
  },
  {
    "id": "W_PL_239",
    "ovr": 70,
    "name": "Medyk Konin",
    "origin": "PL",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PL)",
    "desc": "Ligue 1 Féminine (PL)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (PL)"
  },
  {
    "id": "W_PT_240",
    "ovr": 81,
    "name": "SL Benfica Feminino",
    "origin": "PT",
    "primary": "#E30613",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PT)",
    "desc": "Ligue 1 Féminine (PT)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PT)"
  },
  {
    "id": "W_PT_241",
    "ovr": 80,
    "name": "Sporting CP Feminino",
    "origin": "PT",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PT)",
    "desc": "Ligue 1 Féminine (PT)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (PT)"
  },
  {
    "id": "W_PT_242",
    "ovr": 78,
    "name": "SC Braga Feminino",
    "origin": "PT",
    "primary": "#E30613",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (PT)",
    "desc": "Ligue 1 Féminine (PT)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (PT)"
  },
  {
    "id": "W_PT_243",
    "ovr": 75,
    "name": "FC Famalicão",
    "origin": "PT",
    "primary": "#000080",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PT)",
    "desc": "Ligue 1 Féminine (PT)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PT)"
  },
  {
    "id": "W_PT_244",
    "ovr": 72,
    "name": "Valadares Gaia",
    "origin": "PT",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PT)",
    "desc": "Ligue 1 Féminine (PT)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PT)"
  },
  {
    "id": "W_PT_245",
    "ovr": 70,
    "name": "Clube de Albergaria",
    "origin": "PT",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (PT)",
    "desc": "Ligue 1 Féminine (PT)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (PT)"
  },
  {
    "id": "W_QA_246",
    "ovr": 69,
    "name": "Qatar SC Women",
    "origin": "QA",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (QA)",
    "desc": "Ligue 1 Féminine (QA)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (QA)"
  },
  {
    "id": "W_QA_247",
    "ovr": 68,
    "name": "Al Sadd Women",
    "origin": "QA",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (QA)",
    "desc": "Ligue 1 Féminine (QA)",
    "preferredStat": "physical",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (QA)"
  },
  {
    "id": "W_QA_248",
    "ovr": 67,
    "name": "Al Rayyan Women",
    "origin": "QA",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (QA)",
    "desc": "Ligue 1 Féminine (QA)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (QA)"
  },
  {
    "id": "W_CD_249",
    "ovr": 74,
    "name": "FCF Mazembe",
    "origin": "CD",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CD)",
    "desc": "Ligue 1 Féminine (CD)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CD)"
  },
  {
    "id": "W_CD_250",
    "ovr": 72,
    "name": "CSF Bikira",
    "origin": "CD",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CD)",
    "desc": "Ligue 1 Féminine (CD)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CD)"
  },
  {
    "id": "W_CD_251",
    "ovr": 71,
    "name": "FCF Amani",
    "origin": "CD",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CD)",
    "desc": "Ligue 1 Féminine (CD)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CD)"
  },
  {
    "id": "W_CD_252",
    "ovr": 70,
    "name": "FCF Promesse Star",
    "origin": "CD",
    "primary": "#FFFF00",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CD)",
    "desc": "Ligue 1 Féminine (CD)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CD)"
  },
  {
    "id": "W_SN_253",
    "ovr": 73,
    "name": "Dakar Sacré-Cœur",
    "origin": "SN",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SN)",
    "desc": "Ligue 1 Féminine (SN)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SN)"
  },
  {
    "id": "W_SN_254",
    "ovr": 72,
    "name": "Aigles de la Médina",
    "origin": "SN",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SN)",
    "desc": "Ligue 1 Féminine (SN)",
    "preferredStat": "dribbling",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (SN)"
  },
  {
    "id": "W_SN_255",
    "ovr": 71,
    "name": "Sirènes de Grand Yoff",
    "origin": "SN",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (SN)",
    "desc": "Ligue 1 Féminine (SN)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (SN)"
  },
  {
    "id": "W_SN_256",
    "ovr": 70,
    "name": "Amazones de Grand Yoff",
    "origin": "SN",
    "primary": "#FF0000",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (SN)",
    "desc": "Ligue 1 Féminine (SN)",
    "preferredStat": "finishing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (SN)"
  },
  {
    "id": "W_CH_257",
    "ovr": 77,
    "name": "Servette FCCF",
    "origin": "CH",
    "primary": "#800000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CH)",
    "desc": "Ligue 1 Féminine (CH)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CH)"
  },
  {
    "id": "W_CH_258",
    "ovr": 76,
    "name": "FC Zürich Frauen",
    "origin": "CH",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CH)",
    "desc": "Ligue 1 Féminine (CH)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CH)"
  },
  {
    "id": "W_CH_259",
    "ovr": 74,
    "name": "FC Basel Frauen",
    "origin": "CH",
    "primary": "#FF0000",
    "secondary": "#0000FF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (CH)",
    "desc": "Ligue 1 Féminine (CH)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (CH)"
  },
  {
    "id": "W_CH_260",
    "ovr": 73,
    "name": "Grasshopper Club Zürich",
    "origin": "CH",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CH)",
    "desc": "Ligue 1 Féminine (CH)",
    "preferredStat": "physical",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (CH)"
  },
  {
    "id": "W_CH_261",
    "ovr": 71,
    "name": "BSC YB Frauen",
    "origin": "CH",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CH)",
    "desc": "Ligue 1 Féminine (CH)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CH)"
  },
  {
    "id": "W_CH_262",
    "ovr": 69,
    "name": "FC St. Gallen-Staad",
    "origin": "CH",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (CH)",
    "desc": "Ligue 1 Féminine (CH)",
    "preferredStat": "defense",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (CH)"
  },
  {
    "id": "W_TN_263",
    "ovr": 72,
    "name": "ASF Sahel",
    "origin": "TN",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (TN)",
    "desc": "Ligue 1 Féminine (TN)",
    "preferredStat": "dribbling",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (TN)"
  },
  {
    "id": "W_TN_264",
    "ovr": 71,
    "name": "AS Banque de l'Habitat",
    "origin": "TN",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (TN)",
    "desc": "Ligue 1 Féminine (TN)",
    "preferredStat": "finishing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (TN)"
  },
  {
    "id": "W_TN_265",
    "ovr": 70,
    "name": "US Tunisienne",
    "origin": "TN",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (TN)",
    "desc": "Ligue 1 Féminine (TN)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (TN)"
  },
  {
    "id": "W_TN_266",
    "ovr": 69,
    "name": "ASF Gafsa",
    "origin": "TN",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (TN)",
    "desc": "Ligue 1 Féminine (TN)",
    "preferredStat": "passing",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (TN)"
  },
  {
    "id": "W_TR_267",
    "ovr": 77,
    "name": "Galatasaray Women",
    "origin": "TR",
    "primary": "#FF0000",
    "secondary": "#FFFF00",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (TR)",
    "desc": "Ligue 1 Féminine (TR)",
    "preferredStat": "dribbling",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (TR)"
  },
  {
    "id": "W_TR_268",
    "ovr": 76,
    "name": "Fenerbahçe Women",
    "origin": "TR",
    "primary": "#000080",
    "secondary": "#FFFF00",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (TR)",
    "desc": "Ligue 1 Féminine (TR)",
    "preferredStat": "passing",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (TR)"
  },
  {
    "id": "W_TR_269",
    "ovr": 75,
    "name": "Beşiktaş Women",
    "origin": "TR",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (TR)",
    "desc": "Ligue 1 Féminine (TR)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (TR)"
  },
  {
    "id": "W_TR_270",
    "ovr": 74,
    "name": "ALG Spor",
    "origin": "TR",
    "primary": "#FFFF00",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (TR)",
    "desc": "Ligue 1 Féminine (TR)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (TR)"
  },
  {
    "id": "W_TR_271",
    "ovr": 73,
    "name": "Fomget Gençlik",
    "origin": "TR",
    "primary": "#008000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (TR)",
    "desc": "Ligue 1 Féminine (TR)",
    "preferredStat": "pace",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (TR)"
  },
  {
    "id": "W_TR_272",
    "ovr": 71,
    "name": "Hakkarigücü",
    "origin": "TR",
    "primary": "#FF0000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (TR)",
    "desc": "Ligue 1 Féminine (TR)",
    "preferredStat": "physical",
    "lifestyleFit": "BALANCED",
    "pitch": "Ligue 1 Féminine (TR)"
  },
  {
    "id": "W_UY_273",
    "ovr": 75,
    "name": "Peñarol Femenino",
    "origin": "UY",
    "primary": "#FFFF00",
    "secondary": "#000000",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (UY)",
    "desc": "Ligue 1 Féminine (UY)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (UY)"
  },
  {
    "id": "W_UY_274",
    "ovr": 74,
    "name": "Nacional Femenino",
    "origin": "UY",
    "primary": "#0000FF",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (UY)",
    "desc": "Ligue 1 Féminine (UY)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (UY)"
  },
  {
    "id": "W_UY_275",
    "ovr": 73,
    "name": "Defensor Sporting",
    "origin": "UY",
    "primary": "#800080",
    "secondary": "#FFFFFF",
    "tier": 1,
    "leagueName": "Ligue 1 Féminine (UY)",
    "desc": "Ligue 1 Féminine (UY)",
    "preferredStat": "passing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (UY)"
  },
  {
    "id": "W_UY_276",
    "ovr": 72,
    "name": "Montevideo Wanderers",
    "origin": "UY",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (UY)",
    "desc": "Ligue 1 Féminine (UY)",
    "preferredStat": "defense",
    "lifestyleFit": "STRICT",
    "pitch": "Ligue 1 Féminine (UY)"
  },
  {
    "id": "W_UY_277",
    "ovr": 71,
    "name": "Liverpool Femenino",
    "origin": "UY",
    "primary": "#000000",
    "secondary": "#0000FF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (UY)",
    "desc": "Ligue 1 Féminine (UY)",
    "preferredStat": "finishing",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (UY)"
  },
  {
    "id": "W_UY_278",
    "ovr": 70,
    "name": "Danubio Femenino",
    "origin": "UY",
    "primary": "#000000",
    "secondary": "#FFFFFF",
    "tier": 2,
    "leagueName": "Ligue 1 Féminine (UY)",
    "desc": "Ligue 1 Féminine (UY)",
    "preferredStat": "defense",
    "lifestyleFit": "PARTY",
    "pitch": "Ligue 1 Féminine (UY)"
  }
];
